python:
- "2.7"

script:
# Tells mbed-cli that the current directory is a project even though you didnt do an `mbed import` (helps suppress some warning messages)
- mbed config root .
# Pull in mbed-os and other dependencies
- mbed deploy
- sudo pip install -r mbed-os/requirements.txt
- mbed compile --clean -m K64F -t GCC_ARM
- mbed compile --clean -m K64F -t GCC_ARM --profile debug

before_install:
- sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
- sudo apt-get update -qq
- sudo apt-get install -qq gcc-arm-none-eabi --force-yes
# Print versions we use
- arm-none-eabi-gcc --version
- python --version

install:
- sudo pip install mbed-cli==0.9.10
- sudo pip install pytest
- sudo pip install pylint
- sudo pip install hypothesis
- sudo pip install mock

